source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

# Pods used for development only.
def development_pods
  # A linter to gather code metrics.
  # https://github.com/realm/SwiftLint
  pod 'SwiftLint'

  # Formats the swift code to be consistent.
  # https://github.com/nicklockwood/SwiftFormat
  pod 'SwiftFormat/CLI'
end

# Required pods for the main app.
def app_pods
	# Add pods from embedded frameworks to resolve dependency errors like: dyld Library not loaded, image not found
  shared_pods
  customViews_pods
  serverWorker_pods
  commons_pods

	# Constants for localized text, colors, etc.
	# https://github.com/mac-cain13/R.swift
	pod 'R.swift'

	# A strong typed folder path structure to replace NSSearchPathForDirectoriesInDomains.
	# https://github.com/dreymonde/AppFolder
	pod 'AppFolder'

	# A collection of operators and utilities that simplify iOS layout code.
	# https://github.com/Raizlabs/Anchorage
	pod 'Anchorage'

	# Reactive programming in swift and cocoa.
	# https://github.com/ReactiveX/RxSwift
	pod 'RxSwift'
	pod 'RxCocoa'
end

# Pods used by the Shared framework.
def shared_pods
  # Constants for localized text, storyboards, nibs, etc.
  # https://github.com/mac-cain13/R.swift
  pod 'R.swift'

  # A configurable logger.
	# https://github.com/CocoaLumberjack/CocoaLumberjack
	pod 'CocoaLumberjack/Swift'
end

# Pods used by the DemoWidget extension.
def widget_pods
  # Constants for localized text, colors, etc.
  # https://github.com/mac-cain13/R.swift
  pod 'R.swift'
end

# Pods used by the CustomViews framework.
def customViews_pods
	# A collection of operators and utilities that simplify iOS layout code.
	# https://github.com/Raizlabs/Anchorage
	pod 'Anchorage'
end

# Pods used by the ServerWorker framework.
def serverWorker_pods
end

# Pods used by the Commons framework.
def commons_pods
end


# Targets

target 'DemoAppDev' do
	development_pods
	app_pods
end

target 'DemoAppRelease' do
	app_pods
end

target 'DemoAppUnitTests' do
	development_pods
end

target 'DemoAppUITests' do
	development_pods
end

target 'DemoWidget' do
	development_pods
  widget_pods
end

target 'Shared' do
	development_pods
	shared_pods
end

target 'CustomViews' do
	development_pods
	customViews_pods
end

target 'ServerWorker' do
	development_pods
	serverWorker_pods
end

target 'ServerWorkerTests' do
	# HTTP stubbing.
	# https://github.com/JanGorman/Hippolyte
	pod 'Hippolyte'
end

target 'Commons' do
  development_pods
  commons_pods
end

target 'CommonsTests' do
end


# Post install

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			# Ignore any warnings from pods.
			config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
			config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = "YES"
		end
	end
end
