source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks!

# Pods used for development only.
def development_pods
  # A linter to gather code metrics and enforce Swift style and conventions.
  # https://github.com/realm/SwiftLint
  # License: MIT
  pod 'SwiftLint'

  # Formats the Swift code to be consistent with the coding style guidelines.
  # https://github.com/nicklockwood/SwiftFormat
  # License: MIT
  pod 'SwiftFormat/CLI'
end

# Required pods for the main app.
def app_pods
	# Add pods from embedded frameworks to resolve dependency errors like: dyld Library not loaded, image not found
  shared_pods
  customViews_pods
  serverWorker_pods
  commons_pods

  # Swift code generator creating type-safe constants for localized text, colors, etc.
  # https://github.com/SwiftGen/SwiftGen
  pod 'SwiftGen'

	# A strong typed folder path structure to replace NSSearchPathForDirectoriesInDomains.
	# https://github.com/dreymonde/AppFolder
  # License: MIT
	pod 'AppFolder'

	# A collection of operators and utilities that simplify iOS layout code. Used to create view constraints in code.
	# https://github.com/Raizlabs/Anchorage
  # License: MIT
	pod 'Anchorage'

	# Reactive programming in swift and cocoa.
	# https://github.com/ReactiveX/RxSwift
  # License: MIT
	pod 'RxSwift'
	pod 'RxCocoa'
end

# Pods used by the Shared framework.
def shared_pods
  # Swift code generator creating type-safe constants for localized text, colors, etc.
  # https://github.com/SwiftGen/SwiftGen
  pod 'SwiftGen'

  # A configurable logger.
	# https://github.com/CocoaLumberjack/CocoaLumberjack
  # License: BSD-3-Clause
	pod 'CocoaLumberjack/Swift'
end

# Pods used by the DemoWidget extension.
def widget_pods
end

# Pods used by the CustomViews framework.
def customViews_pods
	# A collection of operators and utilities that simplify iOS layout code. Used to create view constraints in code.
	# https://github.com/Raizlabs/Anchorage
  # License: MIT
	pod 'Anchorage'
end

# Pods used by the ServerWorker framework.
def serverWorker_pods
end

# Pods used by the Commons framework.
def commons_pods
end


# Targets

target 'DemoApp' do
	development_pods
	app_pods
end

target 'DemoAppUnitTests' do
	development_pods
end

target 'DemoAppUITests' do
	development_pods
end

target 'DemoWidget' do
	development_pods
  widget_pods
end

target 'Shared' do
	development_pods
	shared_pods
end

target 'CustomViews' do
	development_pods
	customViews_pods
end

target 'ServerWorker' do
	development_pods
	serverWorker_pods
end

target 'ServerWorkerTests' do
	# HTTP stubbing for mocking HTTP calls so depending classes can be tested.
	# https://github.com/JanGorman/Hippolyte
  # License: MIT
	pod 'Hippolyte'
end

target 'Commons' do
  development_pods
  commons_pods
end

target 'CommonsTests' do
end


# Post install

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			# Ignore any warnings from pods.
			config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
			config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = "YES"
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = "YES"
		end
	end
end
